import { StyleSheet } from '@react-pdf/renderer';

export const styles = StyleSheet.create({
  page: {
    padding: 24,
    fontSize: 9,
    fontFamily: 'Helvetica',
    color: '#1a1a1a',
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    borderBottom: '2px solid #1a1a1a',
    paddingBottom: 8,
    marginBottom: 8,
  },
  companyBlock: { maxWidth: 260 },
  companyName: { fontSize: 16, fontWeight: 700, marginBottom: 2 },
  smallText: { fontSize: 7.5, color: '#333', lineHeight: 1.3 },
  docTitleBlock: { alignItems: 'flex-end' },
  docTitle: { fontSize: 14, fontWeight: 700, marginBottom: 2 },
  docNumber: { fontSize: 9, marginBottom: 2 },
  badge: {
    border: '1px solid #1a1a1a',
    paddingVertical: 2,
    paddingHorizontal: 6,
    fontSize: 7,
    marginTop: 4,
    textAlign: 'center',
  },
  section: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  box: {
    flex: 1,
    border: '1px solid #999',
    padding: 6,
    marginRight: 6,
  },
  boxLast: { marginRight: 0 },
  boxTitle: {
    fontSize: 8,
    fontWeight: 700,
    marginBottom: 4,
    textTransform: 'uppercase',
    color: '#555',
  },
  fieldRow: { flexDirection: 'row', marginBottom: 2 },
  fieldLabel: { width: 65, fontSize: 8, color: '#555' },
  fieldValue: { fontSize: 8.5, flex: 1, fontWeight: 500 },
  table: {
    marginTop: 4,
    marginBottom: 8,
    border: '1px solid #1a1a1a',
  },
  tableRow: { flexDirection: 'row' },
  tableHeaderRow: {
    flexDirection: 'row',
    backgroundColor: '#e8e8e8',
    borderBottom: '1px solid #1a1a1a',
  },
  th: {
    padding: 4,
    fontSize: 7.5,
    fontWeight: 700,
    borderRight: '1px solid #1a1a1a',
  },
  td: {
    padding: 4,
    fontSize: 8.5,
    borderRight: '1px solid #ccc',
    borderTop: '1px solid #ccc',
  },
  colCant: { width: '10%' },
  colDesc: { width: '40%' },
  colImp: { width: '25%', textAlign: 'justify' },
  colTotal: { width: '25%', textAlign: 'justify' },

  price: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },

  totalsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    borderTop: '2px solid #1a1a1a',
    paddingTop: 4,
    marginTop: -1,
  },
  totalLabel: { fontSize: 10, fontWeight: 700, marginRight: 8 },
  totalValue: { fontSize: 12, fontWeight: 700 },
  footerSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  signBox: {
    width: '30%',
    borderTop: '1px solid #1a1a1a',
    paddingTop: 4,
    textAlign: 'center',
    fontSize: 7.5,
  },
  notes: {
    fontSize: 6.5,
    color: '#555',
    lineHeight: 1.4,
    marginTop: 10,
    borderTop: '1px solid #ccc',
    paddingTop: 6,
  },
  trackingFooter: {
    marginTop: 14,
    fontSize: 7,
    textAlign: 'center',
    color: '#555',
  },
});
